name: "🌐 Website issue"
description: "Report a bug or an issue related to the website."
title: "website: [Short Description]"
labels: ["website"]
body:
  - type: textarea
    id: bug-description
    attributes:
      label: Bug description
      description: A clear and concise description of what the bug on the website is.
    validations:
      required: true
  - type: textarea
    id: reproduction-steps
    attributes:
      label: Reproduction steps
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: false
  - type: input
    id: environment
    attributes:
      label: Browser & OS
      description: What browser and operating system are you using? (e.g., Chrome 116 on Windows 11)
    validations:
      required: false
  - type: checkboxes
    id: acknowledgements
    attributes:
      label: Acknowledgements
      options:
        - label: I have searched the existing issues and believe that this is not a duplicate.
          required: true
        - label: This issue is not related to ReVanced, Morphe or any other patch.
          required: true
